/*
 * generated by Xtext 2.35.0
 */
package zeimapeare;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ZeimapeareRuntimeModule extends AbstractZeimapeareRuntimeModule {
}
