/*
 * generated by Xtext 2.35.0
 */
package zeimapeare;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ZeimapeareStandaloneSetup extends ZeimapeareStandaloneSetupGenerated {

	public static void doSetup() {
		new ZeimapeareStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
