/*
 * generated by Xtext 2.35.0
 */
package zeimapeare.validation;

import java.util.List;

import org.eclipse.xtext.validation.Check;

import zeimapeare.zeimapeare.Act;
import zeimapeare.zeimapeare.ActorDeclaration;
import zeimapeare.zeimapeare.ActorParameter;
import zeimapeare.zeimapeare.Program;
import zeimapeare.zeimapeare.Prologue;
import zeimapeare.zeimapeare.Scene;
import zeimapeare.zeimapeare.ZeimapearePackage;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ZeimapeareValidator extends AbstractZeimapeareValidator {
	
//	public static final String INVALID_NAME = "invalidName";
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					ZeimapearePackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	@Check
	public void checkActorEnterToScene(Scene s) {
		
	}
}
